export enum ERROR_CODES {
  CREATE_DIRECTORY = 'ERROR WHEN CREATING A DIRECTORY',
  STEAM_CMD_WORKSHOP = 'DIRECTORY READ ERROR',
  COPY_STEAM_MOD = 'ERROR WHEN COPY MOD',
  STEAM_CODE_ZERO = 'ERROR WHEN DOWNLOAD MOD FROM STEAM',
  ERROR_READ_COLLECTION = 'ERROR WHEN OPEN mods.txt',
}

export enum INFO_CODES {
  CREATE_DIRECTORY = 'DIRECTORY HAS BEEN CREATED',
  COPY_STEAM_MOD = 'INIT COPY STEAM MOD',
}
